version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/joe-app"
    schedule:
      interval: "weekly"
    groups:
      joe-app-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/alquileres"
    schedule:
      interval: "weekly"
    groups:
      alquileres-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
