// Biblioteca de Patrones Editoriales — 15 patrones de composición
// publicitaria premium, cada uno como REGLAS (nunca coordenadas): cómo
// tratar la fotografía, cuánto aire necesita, cuántos elementos tolera,
// si usa iconos, cómo se alinea. Analizan PRINCIPIOS de publicidad real
// (Apple, Nike, Muji, IKEA, retail de lujo...), no copian campañas
// concretas — ningún texto/imagen de terceros vive aquí, solo reglas de
// composición descritas en prosa + números de configuración.
//
// heroTreatment:
//   'full-bleed'        — la foto ocupa el canvas completo, el resto flota encima.
//   'large-borderless'  — foto grande SIN placa/tarjeta/sombra, solo margen alrededor.
//   'framed-minimal'    — única opción que admite una tarjeta, y muy sutil
//                          (línea fina, sin degradado ni sombra pesada) —
//                          reservada a los 2 patrones de catálogo/retail
//                          donde un marco discreto es parte del lenguaje
//                          visual real (no "cajas blancas gigantes").
//
// heroSize: {colRatio, rowRatio} — ignorado si heroTreatment es
// 'full-bleed' (ocupa el 100% por definición).
//
// whitespaceTarget: rango de espacio en blanco que balance-score.js debe
// exigir para ESTE patrón — sustituye al rango único global.
//
// maxElements: cuántos de {hero, logo, title, cta, price, contactFooter,
// icons} puede mostrar la pieza como máximo (hero/price/contactFooter
// nunca se cuentan para recortar — son contenido de negocio ya exigido
// explícitamente por el propietario en un sprint anterior, ver
// art-direction-engine/service.js#decideElements).
//
// preferredStrategies: orden de preferencia sobre las 6 estrategias de
// layout-intelligence/strategies/ — Composition Engine ya no elige por su
// cuenta a partir de compositionId, adapta el layout a lo que el patrón
// ya decidió.

const PATTERNS = [
  {
    id: 'hero-product',
    label: 'Hero Product',
    inspiration: 'Ficha de producto premium — el producto es el único protagonista, todo lo demás es soporte.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.82, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.38, max: 0.58 },
    marginRatio: 0.07,
    allowCard: false,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['centrado-clasico', 'flotante-minimalista'],
    tags: ['general', 'electrodomesticos', 'tecnologia', 'producto'],
  },
  {
    id: 'magazine-editorial',
    label: 'Magazine Editorial',
    inspiration: 'Doble página de revista — foto grande a un lado, bloque de texto respirado al otro.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.64, rowRatio: 0.82 },
    whitespaceTarget: { min: 0.30, max: 0.50 },
    marginRatio: 0.05,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-left',
    preferredStrategies: ['dividido-lifestyle', 'diagonal-dinamico'],
    tags: ['lifestyle', 'editorial', 'moda', 'hogar-decoracion'],
  },
  {
    id: 'luxury-minimal',
    label: 'Luxury Minimal',
    inspiration: 'Joyería/alta gama — casi todo es espacio en blanco, el producto pequeño concentra toda la atención.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.46, rowRatio: 0.34 },
    whitespaceTarget: { min: 0.62, max: 0.80 },
    marginRatio: 0.13,
    allowCard: false,
    maxElements: 3,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flotante-minimalista'],
    tags: ['lujo', 'joyeria', 'belleza', 'general'],
  },
  {
    id: 'apple-style',
    label: 'Apple Style',
    inspiration: 'Producto flotando sobre fondo limpísimo, tipografía mínima, cero decoración.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.74, rowRatio: 0.54 },
    whitespaceTarget: { min: 0.55, max: 0.74 },
    marginRatio: 0.10,
    allowCard: false,
    maxElements: 4,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flotante-minimalista', 'centrado-clasico'],
    tags: ['tecnologia', 'general', 'electrodomesticos'],
  },
  {
    id: 'nike-style',
    label: 'Nike Style',
    inspiration: 'Imagen a sangre completa, energía y movimiento, texto grande y seguro, mínimo adorno.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.18, max: 0.36 },
    marginRatio: 0.05,
    allowCard: false,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'asymmetric-left',
    preferredStrategies: ['cinematico-fullbleed', 'diagonal-dinamico'],
    tags: ['deporte', 'moda', 'general'],
  },
  {
    id: 'muji-style',
    label: 'Muji Style',
    inspiration: 'Calma, materiales naturales, nada de color de acento agresivo, mucho respiro alrededor del producto.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.68, rowRatio: 0.48 },
    whitespaceTarget: { min: 0.55, max: 0.74 },
    marginRatio: 0.10,
    allowCard: false,
    maxElements: 4,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flat-lay-editorial', 'flotante-minimalista'],
    tags: ['hogar-decoracion', 'oficina-papeleria', 'general'],
  },
  {
    id: 'ikea-lifestyle',
    label: 'IKEA Lifestyle',
    inspiration: 'Producto en un hogar real, escena completa, texto integrado sin robarle protagonismo a la escena.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.18, max: 0.35 },
    marginRatio: 0.04,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 3,
    alignment: 'asymmetric-right',
    preferredStrategies: ['dividido-lifestyle', 'cinematico-fullbleed'],
    tags: ['hogar-decoracion', 'mobiliario', 'lifestyle'],
  },
  {
    id: 'product-first',
    label: 'Product First',
    inspiration: 'Ficha técnica de electrodoméstico premium — el producto grande, un pequeño set de datos alrededor.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.86, rowRatio: 0.64 },
    whitespaceTarget: { min: 0.28, max: 0.45 },
    marginRatio: 0.06,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 6,
    alignment: 'center',
    preferredStrategies: ['centrado-clasico', 'cinematico-fullbleed'],
    tags: ['electrodomesticos', 'tecnologia', 'general'],
  },
  {
    id: 'negative-space',
    label: 'Negative Space',
    inspiration: 'El vacío ES el diseño — un objeto diminuto en un mar de espacio en blanco.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.36, rowRatio: 0.26 },
    whitespaceTarget: { min: 0.68, max: 0.85 },
    marginRatio: 0.15,
    allowCard: false,
    maxElements: 3,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flotante-minimalista'],
    tags: ['belleza', 'lujo', 'general'],
  },
  {
    id: 'swiss-grid',
    label: 'Swiss Grid',
    inspiration: 'Tipografía como estructura, alineación estricta, orden absoluto, cero ornamento.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.56, rowRatio: 0.46 },
    whitespaceTarget: { min: 0.40, max: 0.58 },
    marginRatio: 0.06,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 5,
    alignment: 'asymmetric-left',
    preferredStrategies: ['flat-lay-editorial', 'centrado-clasico'],
    tags: ['oficina-papeleria', 'tecnologia', 'general'],
  },
  {
    id: 'asymmetric-editorial',
    label: 'Asymmetric Editorial',
    inspiration: 'Composición asimétrica deliberada, tensión visual controlada, moderno y con actitud.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.58, rowRatio: 0.68 },
    whitespaceTarget: { min: 0.32, max: 0.52 },
    marginRatio: 0.06,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-right',
    preferredStrategies: ['diagonal-dinamico', 'dividido-lifestyle'],
    tags: ['moda', 'general', 'deporte'],
  },
  {
    id: 'poster-design',
    label: 'Poster Design',
    inspiration: 'Cartel de gran formato, alto impacto inmediato, mensaje único y contundente.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.14, max: 0.30 },
    marginRatio: 0.04,
    allowCard: false,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['cinematico-fullbleed'],
    tags: ['general', 'oferta', 'black-friday'],
  },
  {
    id: 'premium-retail',
    label: 'Premium Retail',
    inspiration: 'Ficha de tienda física de gama alta — producto grande sobre una tarjeta discretísima, datos claros.',
    heroTreatment: 'framed-minimal',
    heroSize: { colRatio: 0.76, rowRatio: 0.56 },
    whitespaceTarget: { min: 0.36, max: 0.54 },
    marginRatio: 0.08,
    allowCard: true,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 6,
    alignment: 'center',
    preferredStrategies: ['flat-lay-editorial', 'centrado-clasico'],
    tags: ['electrodomesticos', 'tecnologia', 'oficina-papeleria'],
  },
  {
    id: 'luxury-catalogue',
    label: 'Luxury Catalogue',
    inspiration: 'Catálogo de alta gama, producto enmarcado con una línea finísima, todo muy calmado.',
    heroTreatment: 'framed-minimal',
    heroSize: { colRatio: 0.66, rowRatio: 0.52 },
    whitespaceTarget: { min: 0.48, max: 0.66 },
    marginRatio: 0.10,
    allowCard: true,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flat-lay-editorial'],
    tags: ['lujo', 'joyeria', 'moda'],
  },
  {
    id: 'lifestyle-premium',
    label: 'Lifestyle Premium',
    inspiration: 'Escena de vida real de alta gama — la fotografía manda, el resto es un susurro.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.22, max: 0.40 },
    marginRatio: 0.05,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 3,
    alignment: 'asymmetric-left',
    preferredStrategies: ['cinematico-fullbleed', 'dividido-lifestyle'],
    tags: ['lifestyle', 'hogar-decoracion', 'general'],
  },
];

const DEFAULT_PATTERN_ID = 'hero-product';

module.exports = { PATTERNS, DEFAULT_PATTERN_ID };
