// Biblioteca de Patrones Editoriales — 17 patrones de composición
// publicitaria premium, cada uno como REGLAS (nunca coordenadas): cómo
// tratar la fotografía, cuánto aire necesita, cuántos elementos tolera,
// si usa iconos, cómo se alinea. Analizan PRINCIPIOS de publicidad real
// (Apple, Nike, Muji, IKEA, retail de lujo...), no copian campañas
// concretas — ningún texto/imagen de terceros vive aquí, solo reglas de
// composición descritas en prosa + números de configuración.
//
// heroTreatment:
//   'full-bleed'        — la foto ocupa el canvas completo, el resto flota encima.
//   'large-borderless'  — foto grande SIN placa/tarjeta/sombra, solo margen alrededor.
//   'framed-minimal'    — única opción que admite una tarjeta, y muy sutil
//                          (línea fina, sin degradado ni sombra pesada) —
//                          reservada a los 2 patrones de catálogo/retail
//                          donde un marco discreto es parte del lenguaje
//                          visual real (no "cajas blancas gigantes").
//
// heroSize: {colRatio, rowRatio} — ignorado si heroTreatment es
// 'full-bleed' (ocupa el 100% por definición).
//
// whitespaceTarget: rango de espacio en blanco que balance-score.js debe
// exigir para ESTE patrón — sustituye al rango único global.
//
// maxElements: cuántos de {hero, logo, title, cta, price, contactFooter,
// icons} puede mostrar la pieza como máximo (hero/price/contactFooter
// nunca se cuentan para recortar — son contenido de negocio ya exigido
// explícitamente por el propietario en un sprint anterior, ver
// art-direction-engine/service.js#decideElements).
//
// preferredStrategies: orden de preferencia sobre las 6 estrategias de
// layout-intelligence/strategies/ — Composition Engine ya no elige por su
// cuenta a partir de compositionId, adapta el layout a lo que el patrón
// ya decidió.
//
// Visual Pattern Library (sprint "Visual Reference Intelligence", FASE 2)
// — cada patrón añade además, únicamente como CONCEPTOS reutilizables
// (nunca píxeles ni coordenadas, mismo criterio que reference-library/):
//   conceptAliases   — nombres de concepto con los que un director de arte
//                       humano llamaría a este patrón (algunos se repiten
//                       entre patrones distintos: el mismo concepto puede
//                       resolverse con más de una regla de composición).
//   whenToUse        — cuándo elegirlo.
//   whenToAvoid       — cuándo NO elegirlo, aunque encaje por tags.
//   commonMistakes   — errores reales encontrados y corregidos este mismo
//                       proyecto (sprints "Visual Quality Revolution" y
//                       "Design Eye v1") que afectan específicamente a las
//                       preferredStrategies de este patrón — nunca una
//                       advertencia genérica inventada.
//   projectExamples  — referencia a entradas reales de
//                       reference-library/entries/ que usaron este patrón,
//                       o una nota honesta de que aún no existe ninguna
//                       (no se inventan ejemplos que no se han generado).

const PATTERNS = [
  {
    id: 'hero-product',
    label: 'Hero Product',
    inspiration: 'Ficha de producto premium — el producto es el único protagonista, todo lo demás es soporte.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.84, rowRatio: 0.58 },
    whitespaceTarget: { min: 0.38, max: 0.58 },
    marginRatio: 0.07,
    allowCard: false,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['centrado-clasico', 'flotante-minimalista'],
    tags: ['general', 'electrodomesticos', 'tecnologia', 'producto'],
    conceptAliases: ['Hero dominante'],
    whenToUse: 'Cuando el producto en sí (forma, material, diseño) es el argumento de venta principal y no hay foto de contexto lifestyle real — el producto flota solo, sin escena, confiando en sí mismo. Es el patrón por defecto (DEFAULT_PATTERN_ID) cuando ningún tag encaja mejor.',
    whenToAvoid: 'Si el producto es pequeño o poco fotogénico por sí solo, o si el brief pide transmitir un uso/contexto real ("en el salón de casa") — ahí manda lifestyle-premium o ikea-lifestyle, no este patrón.',
    commonMistakes: 'Comparte preferredStrategies con cinematico-fullbleed, que arrastraba el bug de logo/precio solapados en la esquina superior derecha tras doblar el tamaño del logo (sprint Design Eye v1) — ya corregido (el precio baja debajo del logo si colisionan), pero cualquier ajuste futuro a HIERARCHY_TIER_SPANS.minimo debe re-verificarse contra este patrón con el sweep sintético.',
    projectExamples: 'Sin entrada registrada aún en reference-library — al ser el patrón por defecto, es el que más fácilmente se elige sin foto real; conviene curar una entrada real la próxima vez que produzca una campaña de calidad.',
  },
  {
    id: 'magazine-editorial',
    label: 'Magazine Editorial',
    inspiration: 'Doble página de revista — foto grande a un lado, bloque de texto respirado al otro.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.64, rowRatio: 0.82 },
    whitespaceTarget: { min: 0.30, max: 0.50 },
    marginRatio: 0.05,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-left',
    preferredStrategies: ['dividido-lifestyle', 'diagonal-dinamico'],
    tags: ['lifestyle', 'editorial', 'moda', 'hogar-decoracion'],
    conceptAliases: ['Editorial lifestyle'],
    whenToUse: 'Producto de categoría lifestyle/decoración/moda con foto real disponible y bastante copy (título + varios iconos de beneficio) — el texto necesita su propia columna respirada, no un footer estrecho.',
    whenToAvoid: 'Productos técnicos con pocos argumentos de texto (la columna se siente vacía) o sin foto real de calidad suficiente — con un placeholder, la mitad "revista" no aporta nada.',
    commonMistakes: 'Usa dividido-lifestyle como estrategia primaria — antes del sprint Visual Quality Revolution, ese fichero no tenía protección de desbordamiento en su bucle manual de título/cta/iconos (a diferencia de las 3 estrategias basadas en stackVertically) y podía invadir el footer de contacto. Corregido aplicando el mismo algoritmo de presupuesto restante.',
    projectExamples: 'Sin campaña real registrada aún en reference-library bajo este patrón.',
  },
  {
    id: 'luxury-minimal',
    label: 'Luxury Minimal',
    inspiration: 'Joyería/alta gama — casi todo es espacio en blanco, el producto pequeño concentra toda la atención.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.74, rowRatio: 0.62 },
    whitespaceTarget: { min: 0.62, max: 0.80 },
    marginRatio: 0.13,
    allowCard: false,
    maxElements: 3,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flotante-minimalista'],
    tags: ['lujo', 'joyeria', 'belleza', 'general'],
    conceptAliases: ['Premium minimal'],
    whenToUse: 'Producto de gama alta (joyería, belleza, un único SKU muy cuidado) donde el silencio visual vende más que cualquier dato — casi todo el lienzo es aire, un máximo de 3 elementos.',
    whenToAvoid: 'Campañas con urgencia (black-friday, oferta) o productos que necesitan varios iconos de especificación — maxElements:3 no deja sitio para eso.',
    commonMistakes: 'Antes de Design Eye v1, heroSize (0.46, 0.34) era demasiado pequeño frente a la regla "producto 45-60% del lienzo" — subido a (0.74, 0.62). Cualquier subida futura del hero debe revisar a la vez whitespaceTarget (0.62-0.80), no por separado, o deja de ser coherente con el propio nombre del patrón.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'apple-style',
    label: 'Apple Style',
    inspiration: 'Producto flotando sobre fondo limpísimo, tipografía mínima, cero decoración.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.80, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.55, max: 0.74 },
    marginRatio: 0.10,
    allowCard: false,
    maxElements: 4,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flotante-minimalista', 'centrado-clasico'],
    tags: ['tecnologia', 'general', 'electrodomesticos'],
    conceptAliases: ['Producto flotante', 'Tecnología limpia'],
    whenToUse: 'Tecnología/electrodoméstico con diseño fotogénico y fondo limpio, cero decoración — el producto "flota" sin sombra pesada ni tarjeta, la tipografía mínima hace todo el trabajo de jerarquía.',
    whenToAvoid: 'Cuando hace falta mostrar varios beneficios en iconos (aquí maxIcons:0) o transmitir calidez/hogar — este patrón es frío y quirúrgico a propósito.',
    commonMistakes: 'Comparte flotante-minimalista con luxury-minimal/negative-space/muji-style — sensible al mismo tipo de ajuste de HIERARCHY_TIER_SPANS.minimo (tier del logo); verificar siempre con el sweep sintético tras tocar esa tabla.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'nike-style',
    label: 'Nike Style',
    inspiration: 'Imagen a sangre completa, energía y movimiento, texto grande y seguro, mínimo adorno.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.18, max: 0.36 },
    marginRatio: 0.05,
    allowCard: false,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'asymmetric-left',
    preferredStrategies: ['cinematico-fullbleed', 'diagonal-dinamico'],
    tags: ['deporte', 'moda', 'general'],
    conceptAliases: ['Producto sangrado'],
    whenToUse: 'Categorías con energía/movimiento (deporte, moda, campañas de impacto) con foto real a sangre completa — el texto se ancla asimétrico a la izquierda sobre la foto, sin miedo a tapar parte de la imagen.',
    whenToAvoid: 'Productos estáticos de catálogo (electrodomésticos, oficina) donde "energía y movimiento" no encaja con el tono de marca, o sin una foto real de calidad suficiente para ir a sangre completa.',
    commonMistakes: 'heroTreatment full-bleed + preferredStrategies cinematico-fullbleed/diagonal-dinamico — hereda el bug ya corregido en diagonal-dinamico.js donde un heroSize muy ancho (colRatio ≥0.80, alcanzable por rotación de estrategia) invadía geométricamente la zona de texto; ahora capado con MIN_TEXT_COLUMNS=3.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'muji-style',
    label: 'Muji Style',
    inspiration: 'Calma, materiales naturales, nada de color de acento agresivo, mucho respiro alrededor del producto.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.78, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.55, max: 0.74 },
    marginRatio: 0.10,
    allowCard: false,
    maxElements: 4,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flat-lay-editorial', 'flotante-minimalista'],
    tags: ['hogar-decoracion', 'oficina-papeleria', 'general'],
    conceptAliases: ['Premium minimal'],
    whenToUse: 'Hogar/papelería con estética natural y calmada, sin colores de acento agresivos — mucho respiro alrededor del producto, tono sereno más que quirúrgico.',
    whenToAvoid: 'Ofertas agresivas, o productos tecnológicos "fríos" donde encaja mejor apple-style — muji-style pide calidez, no minimalismo clínico.',
    commonMistakes: 'preferredStrategies incluye flat-lay-editorial, cuyo margen interior (FRAME_INSET_CELLS, layout-intelligence/config.js) es un único valor compartido con swiss-grid/premium-retail/luxury-catalogue/amazon-premium — si se ajusta ahí, revisar los 5 patrones a la vez, no solo uno.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'ikea-lifestyle',
    label: 'IKEA Lifestyle',
    inspiration: 'Producto en un hogar real, escena completa, texto integrado sin robarle protagonismo a la escena.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.18, max: 0.35 },
    marginRatio: 0.04,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 3,
    alignment: 'asymmetric-right',
    preferredStrategies: ['dividido-lifestyle', 'cinematico-fullbleed'],
    tags: ['hogar-decoracion', 'mobiliario', 'lifestyle'],
    conceptAliases: ['Producto sangrado', 'Editorial lifestyle'],
    whenToUse: 'Mobiliario/decoración donde el producto se ve en uso real dentro de una escena de hogar completa — el texto se integra sin robar protagonismo a la escena.',
    whenToAvoid: 'Sin foto de ambiente real y creíble — con un producto aislado sobre fondo blanco, hero-product aporta más que forzar este patrón.',
    commonMistakes: 'Mismo riesgo de desbordamiento en dividido-lifestyle que magazine-editorial/lifestyle-premium (ya corregido), agravado porque además reserva espacio para el logo superpuesto al hero (marcado overlaysHero:true) — la estrategia con menos colchón geométrico de las 6.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'product-first',
    label: 'Product First',
    inspiration: 'Ficha técnica de electrodoméstico premium — el producto grande, un pequeño set de datos alrededor.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.86, rowRatio: 0.56 },
    whitespaceTarget: { min: 0.28, max: 0.45 },
    marginRatio: 0.06,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'center',
    preferredStrategies: ['centrado-clasico', 'cinematico-fullbleed'],
    tags: ['electrodomesticos', 'tecnologia', 'general'],
    conceptAliases: ['Hero dominante'],
    whenToUse: 'Electrodoméstico/tecnología donde hace falta un pequeño set de datos (iconos) alrededor de un producto muy grande — ficha técnica premium, no lifestyle.',
    whenToAvoid: 'Si no hay al menos 2-3 argumentos de venta reales para los iconos — sin señal real en el texto del brief, selectIcons() no rellena nada y la pieza queda desequilibrada respecto al espacio pensado para ellos.',
    commonMistakes: 'heroSize colRatio 0.86 es el más ancho de los 17 patrones — es precisamente el caso que forzó el cap MIN_TEXT_COLUMNS en diagonal-dinamico.js cuando este patrón cae ahí por rotación de estrategia (no es su preferredStrategies primario, pero puede llegar por fallback).',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'negative-space',
    label: 'Negative Space',
    inspiration: 'El vacío ES el diseño — un objeto diminuto en un mar de espacio en blanco.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.76, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.68, max: 0.85 },
    marginRatio: 0.15,
    allowCard: false,
    maxElements: 3,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flotante-minimalista'],
    tags: ['belleza', 'lujo', 'general'],
    conceptAliases: ['Premium minimal'],
    whenToUse: 'Producto muy pequeño y precioso (belleza, lujo) donde el vacío mismo comunica exclusividad — whitespaceTarget más alto de los 17 patrones (0.68-0.85).',
    whenToAvoid: 'Cualquier producto que necesite transmitir volumen/tamaño real, o campañas de oferta donde el vacío se lee como "página sin terminar" en vez de lujo.',
    commonMistakes: 'heroSize (0.36,0.26) original violaba la regla de Design Eye v1 ("producto 45-60% del lienzo") con más margen que ningún otro patrón — subido a (0.76,0.60) manteniendo el whitespace alto vía marginRatio:0.15 (el más alto de los 17) en vez de un hero pequeño, que era la causa real del incumplimiento.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'swiss-grid',
    label: 'Swiss Grid',
    inspiration: 'Tipografía como estructura, alineación estricta, orden absoluto, cero ornamento.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.76, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.40, max: 0.58 },
    marginRatio: 0.06,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-left',
    preferredStrategies: ['flat-lay-editorial', 'centrado-clasico'],
    tags: ['oficina-papeleria', 'tecnologia', 'general'],
    conceptAliases: ['Tecnología limpia', 'Retail moderno'],
    whenToUse: 'Papelería/oficina/tecnología donde la propia tipografía y la alineación estricta son el argumento visual — orden absoluto, ideal cuando hay varios datos que mostrar con disciplina.',
    whenToAvoid: 'Categorías cálidas/lifestyle (hogar-decoracion, moda) donde la rigidez se lee como fría/corporativa en vez de premium.',
    commonMistakes: 'Igual que muji-style/premium-retail/luxury-catalogue/amazon-premium, depende de FRAME_INSET_CELLS (flat-lay-editorial) — cualquier cambio ahí afecta a los 5 patrones a la vez.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'asymmetric-editorial',
    label: 'Asymmetric Editorial',
    inspiration: 'Composición asimétrica deliberada, tensión visual controlada, moderno y con actitud.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.78, rowRatio: 0.62 },
    whitespaceTarget: { min: 0.32, max: 0.52 },
    marginRatio: 0.06,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-right',
    preferredStrategies: ['diagonal-dinamico', 'dividido-lifestyle'],
    tags: ['moda', 'general', 'deporte'],
    conceptAliases: ['Split diagonal'],
    whenToUse: 'Moda/deporte/general con ganas de tensión visual controlada — composición deliberadamente desequilibrada, moderna, con actitud.',
    whenToAvoid: 'Productos que necesitan transmitir calma/confianza (electrodomésticos, papelería seria) — la asimetría deliberada compite con ese tono.',
    commonMistakes: 'preferredStrategies primario es diagonal-dinamico, con heroSize colRatio 0.78 cerca del límite que forzó el cap MIN_TEXT_COLUMNS (ver nike-style) — el bug de invasión de la zona de texto le aplica directamente si algún ajuste futuro sube este heroSize.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'poster-design',
    label: 'Poster Design',
    inspiration: 'Cartel de gran formato, alto impacto inmediato, mensaje único y contundente.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.14, max: 0.30 },
    marginRatio: 0.04,
    allowCard: false,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['cinematico-fullbleed'],
    tags: ['general', 'oferta', 'black-friday'],
    conceptAliases: ['Oferta agresiva'],
    whenToUse: 'Mensaje único y contundente, alto impacto inmediato — black-friday, ofertas puntuales, cuando el objetivo es parar el scroll en un segundo, no explicar el producto en detalle.',
    whenToAvoid: 'Productos que necesitan varios argumentos de venta reales (allowIcons:false, el más restrictivo de los full-bleed) — si el brief trae 3+ beneficios, este patrón los pierde todos.',
    commonMistakes: 'Único preferredStrategies es cinematico-fullbleed, sin alternativa — más expuesto que ningún otro patrón al bug ya corregido de precio/logo solapados en la esquina superior derecha; si ese fichero vuelve a tocarse, probar primero contra este patrón por ser el más dependiente de él.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'premium-retail',
    label: 'Premium Retail',
    inspiration: 'Ficha de tienda física de gama alta — producto grande sobre una tarjeta discretísima, datos claros.',
    heroTreatment: 'framed-minimal',
    heroSize: { colRatio: 0.80, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.36, max: 0.54 },
    marginRatio: 0.08,
    allowCard: true,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'center',
    preferredStrategies: ['flat-lay-editorial', 'centrado-clasico'],
    tags: ['electrodomesticos', 'tecnologia', 'oficina-papeleria'],
    conceptAliases: ['Retail moderno'],
    whenToUse: 'Ficha de tienda física de gama alta con datos claros — uno de los dos únicos patrones (junto a luxury-catalogue) donde una tarjeta discretísima (heroTreatment framed-minimal) está permitida.',
    whenToAvoid: 'Nunca reforzar la tarjeta con sombra pesada o degradado — Design Eye v1 fue explícito en que framed-minimal exige "línea fina, sin degradado ni sombra pesada"; cualquier tentación de "mejorar" la tarjeta rompe el único lenguaje visual que la admite.',
    commonMistakes: 'Comparte flat-lay-editorial (FRAME_INSET_CELLS) con muji-style/swiss-grid/luxury-catalogue/amazon-premium — ver arriba.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'luxury-catalogue',
    label: 'Luxury Catalogue',
    inspiration: 'Catálogo de alta gama, producto enmarcado con una línea finísima, todo muy calmado.',
    heroTreatment: 'framed-minimal',
    heroSize: { colRatio: 0.78, rowRatio: 0.60 },
    whitespaceTarget: { min: 0.48, max: 0.66 },
    marginRatio: 0.10,
    allowCard: true,
    maxElements: 5,
    allowIcons: false,
    maxIcons: 0,
    alignment: 'center',
    preferredStrategies: ['flat-lay-editorial'],
    tags: ['lujo', 'joyeria', 'moda'],
    conceptAliases: ['Catálogo premium'],
    whenToUse: 'Catálogo de alta gama (joyería, moda de lujo) con marco finísimo alrededor del producto, todo muy calmado — el segundo (y último) patrón que admite tarjeta.',
    whenToAvoid: 'Sin foto de producto realmente cuidada (el marco fino hace más evidente cualquier foto de baja calidad, al contrario que full-bleed, que la disimula) — y nunca con iconos, aquí siempre desactivados.',
    commonMistakes: 'Mismo riesgo framed-minimal que premium-retail: la tentación de añadir sombra/degradado al marco cuando "no se ve suficiente".',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'lifestyle-premium',
    label: 'Lifestyle Premium',
    inspiration: 'Escena de vida real de alta gama — la fotografía manda, el resto es un susurro.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.22, max: 0.40 },
    marginRatio: 0.05,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 3,
    alignment: 'asymmetric-left',
    preferredStrategies: ['cinematico-fullbleed', 'dividido-lifestyle'],
    tags: ['lifestyle', 'hogar-decoracion', 'general'],
    conceptAliases: ['Editorial lifestyle', 'Producto sangrado'],
    whenToUse: 'Cuando existe una foto lifestyle REAL (no genérica de stock) de calidad — la fotografía manda, todo el texto (título, precio, cta, footer) flota encima con jerarquía marcada, sin bloque de color aparte. Es el patrón que produjo la campaña real del Ventilador Nebulizador Muvip tras el sprint Visual Quality Revolution.',
    whenToAvoid: 'Con placeholder o foto genérica de stock (selectPattern ya penaliza esto al no sumar el bonus de hasRealPhoto+lifestyle, pero no conviene forzarlo a mano en ese caso) — y cuando hace falta una fila de iconos de especificaciones técnicas, porque solo hay sitio cómodo para titular+precio+cta+footer.',
    commonMistakes: 'Documentado en detalle en reference-library/entries/campana-ofipapel_ventilador-visual-quality-v2.json — resumen: el título debe compartir zona con decoraciones color-band/diagonal-accent (titleNeedsLightText() decide texto claro/oscuro), y el CTA no debe ser lo primero que se recorte si maxElements se excede (CUT_PRIORITY ya corregido).',
    projectExamples: 'campana-ofipapel_ventilador-visual-quality-v2 (post Visual Quality Revolution + Design Eye v1) y campana-ofipapel_ventilador-nebulizador-75w-40cm-con-mand_2026-07-26T11-59-04-716Z_d6405511-v1 (versión anterior, aún válida para su propia época) en reference-library/entries/.',
  },
  {
    id: 'amazon-premium',
    label: 'Amazon Premium',
    inspiration: 'Ficha de marketplace de gama alta — producto grande sobre blanco limpio, especificaciones claras en iconos, precio inconfundible en la esquina, cero ruido visual.',
    heroTreatment: 'large-borderless',
    heroSize: { colRatio: 0.80, rowRatio: 0.62 },
    whitespaceTarget: { min: 0.34, max: 0.52 },
    marginRatio: 0.055,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-right',
    preferredStrategies: ['flat-lay-editorial', 'centrado-clasico'],
    tags: ['tecnologia', 'electrodomesticos', 'general', 'oferta'],
    conceptAliases: ['Precio protagonista', 'Retail moderno'],
    whenToUse: 'Ficha de marketplace de gama alta — precio inconfundible en la esquina, especificaciones en iconos claros, cero ruido. Ideal cuando el precio es un argumento de venta fuerte (buena relación calidad-precio) y hay datos técnicos reales para 3-4 iconos.',
    whenToAvoid: 'Productos de lujo/joyería donde mostrar el precio de forma tan directa rompe el tono aspiracional (ahí luxury-catalogue o negative-space) — y sin datos técnicos reales, allowIcons:true no debe rellenarse con relleno.',
    commonMistakes: 'flat-lay-editorial como estrategia preferida — mismo FRAME_INSET_CELLS compartido con muji-style/swiss-grid/premium-retail/luxury-catalogue.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
  {
    id: 'mediamarkt-editorial',
    label: 'MediaMarkt Editorial',
    inspiration: 'Folleto de electrónica de alto impacto — foto a sangre completa, energía y urgencia, precio y CTA compitiendo por atención inmediata, acento diagonal con banda de color.',
    heroTreatment: 'full-bleed',
    heroSize: null,
    whitespaceTarget: { min: 0.16, max: 0.32 },
    marginRatio: 0.045,
    allowCard: false,
    maxElements: 6,
    allowIcons: true,
    maxIcons: 4,
    alignment: 'asymmetric-right',
    preferredStrategies: ['diagonal-dinamico', 'cinematico-fullbleed'],
    tags: ['tecnologia', 'electrodomesticos', 'oferta', 'black-friday'],
    conceptAliases: ['Oferta agresiva', 'Split diagonal'],
    whenToUse: 'Electrónica con urgencia real (black-friday, oferta) — precio y CTA compitiendo por atención inmediata, acento diagonal de color que refuerza la sensación de folleto de alto impacto.',
    whenToAvoid: 'Fuera de contexto de oferta/urgencia (campañas evergreen, gama alta) — el acento diagonal agresivo se lee como rebajas incluso sin decirlo explícitamente.',
    commonMistakes: 'preferredStrategies primario diagonal-dinamico + heroTreatment full-bleed — la combinación más expuesta al bug ya corregido de texto ilegible sobre decoración de color (titleNeedsLightText()), porque el título vive justo sobre el acento diagonal por diseño, no por accidente.',
    projectExamples: 'Sin campaña real registrada aún.',
  },
];

const DEFAULT_PATTERN_ID = 'hero-product';

module.exports = { PATTERNS, DEFAULT_PATTERN_ID };
