// Biblioteca atómica: ESTILOS (52 entradas — supera el mínimo de 50
// pedido). El "género"/mood general de la pieza. Ver libraries/index.js
// para el contrato {id,label,text,tags}.

module.exports = [
  { id: 'editorial-minimalista', label: 'Editorial minimalista', text: 'estilo editorial minimalista, mucho espacio en blanco, composición depurada', tags: ['general', 'tecnologia', 'oficina-papeleria', 'belleza'] },
  { id: 'producto-flotante-estudio', label: 'Producto flotante de estudio', text: 'producto flotando sobre fondo de estudio, sombra suave proyectada, catálogo publicitario clásico', tags: ['general', 'electrodomesticos', 'tecnologia'] },
  { id: 'lifestyle-documental', label: 'Lifestyle documental', text: 'fotografía lifestyle editorial de nivel revista de decoración de interiores, calidad de campaña publicitaria real de marca premium — un momento cotidiano genuino, capturado como si el fotógrafo hubiera esperado el instante correcto en vez de dirigir una pose; si hay una persona en el encuadre, su gesto es relajado y espontáneo, nunca mirando directamente a cámara ni posando de catálogo', tags: ['general', 'hogar-decoracion', 'alimentacion'] },
  { id: 'retrofuturista', label: 'Retrofuturista', text: 'estética retrofuturista, colores saturados de los 70-80 con un toque futurista', tags: ['tecnologia', 'general'] },
  { id: 'maximalista-color-bloque', label: 'Maximalista, color-bloque', text: 'maximalismo de color, bloques de color puro y contrastado como fondo', tags: ['moda', 'general', 'belleza'] },
  { id: 'brutalista-industrial', label: 'Brutalista industrial', text: 'estética brutalista, hormigón y metal crudo, tipografía imaginaria pesada (sin renderizar texto)', tags: ['tecnologia', 'mobiliario'] },
  { id: 'organico-natural', label: 'Orgánico natural', text: 'materiales orgánicos, madera, piedra, plantas — sensación natural y cálida', tags: ['hogar-decoracion', 'alimentacion', 'belleza'] },
  { id: 'corporativo-limpio', label: 'Corporativo limpio', text: 'estilo corporativo limpio, confiable, colores neutros y composición ordenada', tags: ['oficina-papeleria', 'general'] },
  { id: 'lujo-oscuro', label: 'Lujo oscuro', text: 'fondo oscuro elegante, acentos dorados o metálicos, sensación de producto premium', tags: ['joyeria', 'belleza', 'general'] },
  { id: 'pastel-soft', label: 'Pastel suave', text: 'paleta pastel suave, luz difusa, sensación amable y accesible', tags: ['infantil', 'belleza', 'hogar-decoracion'] },
  { id: 'alto-contraste-drama', label: 'Alto contraste dramático', text: 'alto contraste, sombras marcadas, sensación dramática y potente', tags: ['deporte', 'automocion', 'tecnologia'] },
  { id: 'vintage-analogico', label: 'Vintage analógico', text: 'textura de grano de película analógica, colores ligeramente desaturados, nostalgia', tags: ['moda', 'general'] },
  { id: 'pop-art', label: 'Pop art', text: 'estilo pop-art, colores planos muy saturados, alto impacto visual', tags: ['moda', 'infantil', 'general'] },
  { id: 'escandinavo-nordico', label: 'Escandinavo nórdico', text: 'minimalismo escandinavo, tonos claros, madera clara, luz natural fría', tags: ['hogar-decoracion', 'mobiliario', 'oficina-papeleria'] },
  { id: 'artesanal-hecho-a-mano', label: 'Artesanal, hecho a mano', text: 'sensación artesanal, texturas imperfectas y cálidas, hecho a mano', tags: ['alimentacion', 'hogar-decoracion'] },
  { id: 'tecnologico-futurista', label: 'Tecnológico futurista', text: 'estética tecnológica futurista, superficies limpias, luces frías tipo led', tags: ['tecnologia', 'electrodomesticos'] },
  { id: 'cinematografico', label: 'Cinematográfico', text: 'iluminación y encuadre cinematográficos, sensación de fotograma de película', tags: ['automocion', 'general', 'deporte'] },
  { id: 'surrealista-conceptual', label: 'Surrealista conceptual', text: 'composición surrealista conceptual, elementos inesperados que refuerzan la idea del producto', tags: ['moda', 'general'] },
  { id: 'grunge-textura', label: 'Grunge con textura', text: 'texturas ásperas tipo grunge, superficies desgastadas, energía urbana', tags: ['moda', 'deporte'] },
  { id: 'monocromo-elegante', label: 'Monocromo elegante', text: 'paleta prácticamente monocroma, elegancia por contraste tonal, no por color', tags: ['joyeria', 'belleza', 'general'] },
  { id: 'collage-mixto', label: 'Collage de medios mixtos', text: 'sensación de collage de medios mixtos, capas y recortes', tags: ['moda', 'general'] },
  { id: 'minimalismo-japones-wabi-sabi', label: 'Minimalismo japonés (wabi-sabi)', text: 'minimalismo japonés wabi-sabi, belleza en la imperfección, espacio negativo generoso', tags: ['hogar-decoracion', 'belleza'] },
  { id: 'street-style-urbano', label: 'Street style urbano', text: 'energía de street style urbano, fondo de ciudad desenfocado', tags: ['moda', 'deporte'] },
  { id: 'estudio-alta-key', label: 'Estudio de alta clave (high-key)', text: 'iluminación de alta clave, fondo blanco puro, sombras mínimas', tags: ['general', 'electrodomesticos', 'belleza'] },
  { id: 'estudio-baja-key', label: 'Estudio de baja clave (low-key)', text: 'iluminación de baja clave, fondo oscuro, mucho contraste', tags: ['tecnologia', 'joyeria'] },
  { id: 'producto-en-movimiento', label: 'Producto en movimiento', text: 'sensación de movimiento capturado, producto en plena acción', tags: ['electrodomesticos', 'deporte'] },
  { id: 'despiece-tecnico', label: 'Despiece técnico', text: 'estilo de despiece técnico, componentes o características señaladas visualmente', tags: ['tecnologia', 'electrodomesticos'] },
  { id: 'antes-despues', label: 'Antes / después', text: 'composición de contraste antes-después, transformación visible', tags: ['hogar-decoracion', 'belleza'] },
  { id: 'comparativa-tamano-escala', label: 'Comparativa de escala', text: 'producto junto a un elemento cotidiano que ayuda a entender su tamaño real', tags: ['electrodomesticos', 'mobiliario'] },
  { id: 'hero-shot-heroico', label: 'Hero shot heroico', text: 'plano héroe, producto como protagonista absoluto, ángulo que engrandece', tags: ['general', 'tecnologia', 'automocion'] },
  { id: 'flat-lay-cenital', label: 'Flat lay cenital', text: 'composición flat-lay vista desde arriba, elementos ordenados sobre superficie plana', tags: ['alimentacion', 'oficina-papeleria', 'moda'] },
  { id: 'unboxing-experiencial', label: 'Unboxing experiencial', text: 'sensación de unboxing, packaging abierto, momento de descubrimiento', tags: ['tecnologia', 'general'] },
  { id: 'estacional-navideno', label: 'Estacional navideño', text: 'ambientación navideña, luces cálidas, elementos festivos discretos', tags: ['general', 'alimentacion', 'hogar-decoracion'] },
  { id: 'estacional-veraniego', label: 'Estacional veraniego', text: 'ambientación veraniega, luz solar brillante, sensación de frescor', tags: ['electrodomesticos', 'general', 'alimentacion'] },
  { id: 'mediterraneo-canario', label: 'Mediterráneo / canario', text: 'ambientación mediterránea-canaria, luz cálida de exterior, tonos tierra y azul', tags: ['general', 'alimentacion', 'hogar-decoracion'] },
  { id: 'rustico-campestre', label: 'Rústico campestre', text: 'ambientación rústica campestre, madera envejecida, luz natural cálida', tags: ['alimentacion', 'hogar-decoracion'] },
  { id: 'neon-cyberpunk', label: 'Neón cyberpunk', text: 'iluminación neón cyberpunk, contraste de colores fríos y cálidos saturados', tags: ['tecnologia', 'deporte'] },
  { id: 'acuarela-ilustrado-hibrido', label: 'Híbrido acuarela/ilustrado', text: 'fondo con textura de acuarela ilustrada combinado con fotografía real del producto', tags: ['infantil', 'moda'] },
  { id: 'geometrico-abstracto', label: 'Geométrico abstracto', text: 'formas geométricas abstractas de fondo, composición ordenada y moderna', tags: ['tecnologia', 'oficina-papeleria', 'general'] },
  { id: 'papel-recortado-craft', label: 'Papel recortado (craft)', text: 'estética de papel recortado craft, capas con sombra suave', tags: ['oficina-papeleria', 'infantil'] },
  { id: 'reflejos-espejo-agua', label: 'Reflejos de espejo/agua', text: 'superficie reflectante tipo espejo o agua, duplicando el producto con elegancia', tags: ['belleza', 'joyeria', 'tecnologia'] },
  { id: 'humo-niebla-atmosferico', label: 'Humo/niebla atmosférico', text: 'ambiente con humo o niebla ligera, sensación atmosférica y misteriosa', tags: ['electrodomesticos', 'belleza', 'general'] },
  { id: 'gradiente-suave-degradado', label: 'Gradiente suave', text: 'fondo con degradado de color suave, moderno y limpio', tags: ['tecnologia', 'general', 'belleza'] },
  { id: 'textura-tela-organica', label: 'Textura de tela orgánica', text: 'fondo con textura de tela natural (lino, algodón crudo)', tags: ['moda', 'hogar-decoracion'] },
  { id: 'metal-industrial-frio', label: 'Metal industrial frío', text: 'superficies metálicas industriales, tonos fríos, sensación de robustez', tags: ['electrodomesticos', 'tecnologia'] },
  { id: 'luz-natural-casera', label: 'Luz natural casera', text: 'luz natural de interior doméstico, sensación auténtica y cercana, no de estudio', tags: ['hogar-decoracion', 'alimentacion', 'general'] },
  { id: 'estudio-publicitario-clasico', label: 'Estudio publicitario clásico', text: 'estilo de estudio publicitario clásico de catálogo, muy limpio y neutro', tags: ['general', 'oficina-papeleria', 'electrodomesticos'] },
  { id: 'redes-sociales-nativo-casual', label: 'Nativo de redes sociales (casual)', text: 'estética nativa de redes sociales, casual, poco producida a propósito, sensación auténtica', tags: ['general', 'moda', 'alimentacion'] },
  { id: 'producto-heroe-flotante-sombra', label: 'Héroe flotante con sombra dramática', text: 'producto flotante con sombra dramática y alargada, gran protagonismo', tags: ['tecnologia', 'general'] },
  { id: 'blanco-y-negro-editorial', label: 'Blanco y negro editorial', text: 'fotografía en blanco y negro de estilo editorial, foco en forma y textura', tags: ['moda', 'joyeria', 'general'] },
  { id: 'color-vibrante-verano', label: 'Color vibrante de verano', text: 'colores vibrantes y saturados de verano, alta energía visual', tags: ['electrodomesticos', 'general', 'moda'] },
  { id: 'dark-academia-elegante', label: 'Dark academia elegante', text: 'estética dark academia, tonos tierra oscuros, sensación intelectual y elegante', tags: ['oficina-papeleria', 'general'] },
];
